# Source secrets file which holds environment
# variables for things such as tokens
source "$HOME/.secrets"

#
# Setup
#

source "$HOME"/.dotfiles-shared/shrc-setup-homebrew
source "$HOME"/.dotfiles-shared/shrc-setup-thefuck
source "$HOME"/.dotfiles-shared/shrc-setup-nvm
source "$HOME"/.dotfiles-shared/shrc-setup-chruby
source "$HOME"/.dotfiles-shared/shrc-setup-rust
source "$HOME"/.dotfiles-shared/shrc-setup-android-studio

# Add flutter binaries to path
export PATH="$PATH:${HOME}/flutter/bin"

# Use Java 1.8 by default, because react-native
if [[ "${OSTYPE}" == darwin* ]]; then
  export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
fi

#
# Utility Functions
#

source "$HOME"/.dotfiles-shared/shrc-utility


#### FIG ENV VARIABLES ####
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####


