# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && . "$HOME/.fig/shell/zshrc.pre.zsh"

# Source secrets file which holds environment
# variables for things such as tokens
source "$HOME/.secrets"

#
# Setup
#

source "$HOME"/.dotfiles-shared/shrc-setup-zsh
source "$HOME"/.dotfiles-shared/shrc-setup-homebrew
source "$HOME"/.dotfiles-shared/shrc-setup-thefuck
source "$HOME"/.dotfiles-shared/shrc-setup-nvm
source "$HOME"/.dotfiles-shared/shrc-setup-chruby
source "$HOME"/.dotfiles-shared/shrc-setup-android-studio

# Use Java 1.8 by default, because react-native
if [[ "${OSTYPE}" == darwin* ]]; then
  export JAVA_HOME="$(/usr/libexec/java_home -v 1.8 | grep jdk)"
fi

# Set default editors
export VISUAL=vim
export EDITOR="${VISUAL}"
export REACT_EDITOR=code

#
# Aliases
#

source "$HOME"/.dotfiles-shared/shrc-alias-git

alias .p="cd ~/projects"

alias .bin="bundle install --path=vendor/bundle"
alias .bup="bundle update"
alias .bx="bundle exec"

alias .pin="pod install"
alias .pup="pod update"

alias .cloud="sudo ifconfig awdl0 down"

#
# Utility Functions
#

source "$HOME"/.dotfiles-shared/shrc-utility

#
# Custom Shell Prompt
#

eval "$(starship init zsh)"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && . "$HOME/.fig/shell/zshrc.post.zsh"
