# Source secrets file which holds environment
# variables for things such as tokens
source "$HOME/.secrets"

#
# Setup
#

source "$HOME"/.dotfiles-shared/shrc-setup-homebrew
source "$HOME"/.dotfiles-shared/shrc-setup-zsh
source "$HOME"/.dotfiles-shared/shrc-setup-thefuck
source "$HOME"/.dotfiles-shared/shrc-setup-nvm
source "$HOME"/.dotfiles-shared/shrc-setup-chruby
source "$HOME"/.dotfiles-shared/shrc-setup-android-sdk-linux

# Set default editors
export VISUAL=vim
export EDITOR="${VISUAL}"
export REACT_EDITOR=code

#
# Aliases
#

source "$HOME"/.dotfiles-shared/shrc-alias-git

alias .w="cd ~/workspace"

alias .bin="bundle install --path=vendor/bundle"
alias .bup="bundle update"
alias .bx="bundle exec"

alias .pin="pod install"
alias .pup="pod update"

alias .s="ddgr"

#
# Utility Functions
#

source "$HOME"/.dotfiles-shared/shrc-utility

#
# Custom Shell Prompt
#

eval "$(starship init zsh)"
