#
# Setup
#

source "$HOME"/.dotfiles-shared/shrc-setup-homebrew
source "$HOME"/.dotfiles-shared/shrc-setup-android-studio

#
# Utility Functions
#

source "$HOME"/.dotfiles-shared/shrc-utility


. "$HOME/.local/bin/env"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/barissencan/.lmstudio/bin"
# End of LM Studio CLI section
