# Source secrets file which holds environment
# variables for things such as tokens
source "$HOME/.secrets"

#
# Setup
#

source "$HOME"/.dotfiles-shared/shrc-setup-zsh
source "$HOME"/.dotfiles-shared/shrc-setup-homebrew
source "$HOME"/.dotfiles-shared/shrc-setup-thefuck
source "$HOME"/.dotfiles-shared/shrc-setup-nvm
source "$HOME"/.dotfiles-shared/shrc-setup-chruby
source "$HOME"/.dotfiles-shared/shrc-setup-android-studio

# Use Java 1.8 by default, because react-native
if [[ "${OSTYPE}" == darwin* ]]; then
  export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
fi

# Set default editors
export VISUAL=vim
export EDITOR="${VISUAL}"
export REACT_EDITOR=code

#
# Aliases
#

source "$HOME"/.dotfiles-shared/shrc-alias-git

alias lynx="lynx -cfg=$HOME/.lynxrc"

alias .p="cd ~/projects"

alias .bin="bundle install"
alias .bup="bundle update"
alias .bx="bundle exec"

alias .pin="pod install"
alias .pup="pod update"

alias .s="ddgr"

#
# Utility Functions
#

source "$HOME"/.dotfiles-shared/shrc-utility

#
# Custom Shell Prompt
#

eval "$(starship init zsh)"